//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ar_Project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ar_Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font_awesome_4_7_0_check_circle_o_87_0_2bf480_none {
            get {
                object obj = ResourceManager.GetObject("font_awesome_4_7_0_check_circle_o_87_0_2bf480_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPEhtml&gt;
        ///&lt;html lang=&apos;ar&apos;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&apos;utf-8&apos;&gt;
        ///&lt;/head&gt;
        ///&lt;style&gt;
        ///table, th, td {
        ///    border: 1px solid black;
        ///    text-align: center;
        ///}
        ///&lt;/style&gt;
        ///&lt;body dir=&apos;rtl&apos;&gt;&lt;Center&gt;
        ///
        ///
        ///&lt;br&gt;
        ///&lt;div class=&apos;wid&apos; style=&quot;Width=&apos;40%&apos;&quot;&gt;
        ///&lt;table border=&quot;pix&quot;&gt;
        ///    &lt;th&gt;   اسم المنتج  &lt;/th&gt;
        ///    &lt;th&gt;   سعر المنتج  &lt;/th&gt;
        ///    &lt;th&gt;   كمية المنتج  &lt;/th&gt;
        ///    &lt;th&gt;   رقم الباركود  &lt;/th&gt;
        ///    
        ///    &lt;%&gt;
        ///    
        ///&lt;/table&gt;
        ///
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;/Center&gt;
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string Htmlfile {
            get {
                return ResourceManager.GetString("Htmlfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ionicons_2_0_1_ios_timer_23_0_27ae60_none {
            get {
                object obj = ResourceManager.GetObject("ionicons_2_0_1_ios_timer_23_0_27ae60_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap material_icons_3_0_1_done_23_0_27ae60_none {
            get {
                object obj = ResourceManager.GetObject("material_icons_3_0_1_done_23_0_27ae60_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap material_icons_3_0_1_timer_87_0_2bf480_none {
            get {
                object obj = ResourceManager.GetObject("material_icons_3_0_1_timer_87_0_2bf480_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
